services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: jobsearch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobsearch-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: jobsearch
      JWT_SECRET: your-secret-key-here
      PORT: 8080
    depends_on:
      - postgres
    networks:
      - jobsearch-network

  seed:
    build: 
      context: ./backend
      dockerfile: Dockerfile.seed
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: jobsearch
      JWT_SECRET: your-secret-key-here
    depends_on:
      - postgres
    networks:
      - jobsearch-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - jobsearch-network
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - jobsearch-network

volumes:
  postgres_data:

networks:
  jobsearch-network:
    driver: bridge

