openapi: 3.0.0
info:
  title: Job Search API
  version: 1.0.0
  description: API для приложения поиска работы

servers:
  - url: http://localhost:8080/api
    description: Локальный сервер

paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
                name:
                  type: string
                role:
                  type: string
                  enum: [job_seeker, employer, admin]
              required: [email, password]
      responses:
        '201':
          description: Пользователь создан
        '400':
          description: Ошибка валидации
        '409':
          description: Пользователь уже существует

  /auth/login:
    post:
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Успешная авторизация
        '400':
          description: Ошибка валидации
        '401':
          description: Неверные учетные данные

  /jobs:
    get:
      summary: Получение списка вакансий
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Список вакансий
        '500':
          description: Ошибка сервера

  /jobs/{id}:
    get:
      summary: Получение вакансии по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Вакансия найдена
        '400':
          description: Некорректный ID
        '404':
          description: Вакансия не найдена

  /applications:
    post:
      summary: Подача заявки на вакансию
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                job_id:
                  type: integer
                cover_letter:
                  type: string
              required: [job_id]
      responses:
        '201':
          description: Заявка подана
        '401':
          description: Не авторизован
        '400':
          description: Ошибка валидации

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
